all:
	make -C asm all
	make -C corewar all

clean:
	make -C asm clean
	make -C corewar clean

fclean:
	make -C asm fclean
	make -C corewar fclean

re:
	make -C asm fclean all
	make -C corewar fclean all
